/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/login/ — 以 email + password 換取 JWT，回應附帶 user。 */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/logout/ — 將傳入的 refresh token 加入黑名單。 */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/register/ — 註冊成功後直接回傳 user 與 JWT。 */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_users_partial_update"];
        trace?: never;
    };
    "/api/ledger/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_accounts_list"];
        put?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        post: operations["ledger_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/accounts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_accounts_retrieve"];
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        put: operations["ledger_accounts_update"];
        post?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        delete: operations["ledger_accounts_destroy"];
        options?: never;
        head?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        patch: operations["ledger_accounts_partial_update"];
        trace?: never;
    };
    "/api/ledger/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_categories_list"];
        put?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        post: operations["ledger_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_categories_retrieve"];
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        put: operations["ledger_categories_update"];
        post?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        delete: operations["ledger_categories_destroy"];
        options?: never;
        head?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        patch: operations["ledger_categories_partial_update"];
        trace?: never;
    };
    "/api/ledger/recurring-rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_recurring_rules_list"];
        put?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        post: operations["ledger_recurring_rules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/recurring-rules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_recurring_rules_retrieve"];
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        put: operations["ledger_recurring_rules_update"];
        post?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        delete: operations["ledger_recurring_rules_destroy"];
        options?: never;
        head?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        patch: operations["ledger_recurring_rules_partial_update"];
        trace?: never;
    };
    "/api/ledger/reports/balance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 總餘額與各帳戶餘額
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_balance_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/balance-history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 每帳戶逐月餘額（連續月份、缺月沿用前值）
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_balance_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/savings-goal-status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 儲蓄目標達成狀態（帶 month＝月度、省略＝年度）
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_savings_goal_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定月收支
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/summary/by-category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定月各分類收支（單值 FK，各桶加總＝當月總額）
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_summary_by_category_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/summary/by-tag/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定月各標籤收支（M2M 可重疊維度，不可加總當總額）
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_summary_by_tag_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/summary/range/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 任意日期區間收支
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_summary_range_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/reports/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 今日（當前時區）收支
         * @description 唯讀報表端點集合（/api/ledger/reports/…）：各 action 委派 reports.py 的純函式。
         *
         *     用 ViewSet（非 ModelViewSet）：報表不是 CRUD 資源、無單一 queryset/序列化器；每支都吃
         *     request.user 過濾，資安邊界落在 reports 函式內。
         */
        get: operations["ledger_reports_today_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/savings-goals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_savings_goals_list"];
        put?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        post: operations["ledger_savings_goals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/savings-goals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_savings_goals_retrieve"];
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        put: operations["ledger_savings_goals_update"];
        post?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        delete: operations["ledger_savings_goals_destroy"];
        options?: never;
        head?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        patch: operations["ledger_savings_goals_partial_update"];
        trace?: never;
    };
    "/api/ledger/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_tags_list"];
        put?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        post: operations["ledger_tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/tags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_tags_retrieve"];
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        put: operations["ledger_tags_update"];
        post?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        delete: operations["ledger_tags_destroy"];
        options?: never;
        head?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        patch: operations["ledger_tags_partial_update"];
        trace?: never;
    };
    "/api/ledger/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_transactions_list"];
        put?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        post: operations["ledger_transactions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/transactions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        get: operations["ledger_transactions_retrieve"];
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        put: operations["ledger_transactions_update"];
        post?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        delete: operations["ledger_transactions_destroy"];
        options?: never;
        head?: never;
        /**
         * @description 業務資源共用基底：強制登入 + 依 request.user 做資料隔離。
         *
         *     - get_queryset：把可見資料限縮到當前使用者（別人的物件不在集合內 → 讀/改/刪皆 404）。
         *     - perform_create：寫入時把 user 設為當前使用者，無視 client 夾帶的 user。
         *     - 分頁：list 一律回 count/next/previous/results 信封（LedgerPagination）。
         *
         *     五個資源共用這一份，資安邊界只有一處要審。
         */
        patch: operations["ledger_transactions_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            type: components["schemas"]["AccountTypeEnum"];
            /** Format: decimal */
            readonly balance: string;
            is_default?: boolean;
        };
        /**
         * @description * `cash` - 現金
         *     * `bank` - 銀行
         *     * `credit_card` - 信用卡
         *     * `e_wallet` - 電子錢包
         * @enum {string}
         */
        AccountTypeEnum: "cash" | "bank" | "credit_card" | "e_wallet";
        BalanceHistoryAccount: {
            /** Format: uuid */
            account_id: string;
            account_name: string;
            months: components["schemas"]["BalanceHistoryMonth"][];
        };
        BalanceHistoryMonth: {
            /** @description YYYY-MM */
            month: string;
            /** Format: decimal */
            balance: string;
        };
        BalanceOverview: {
            /** Format: decimal */
            total_balance: string;
            accounts: components["schemas"]["BalanceOverviewAccount"][];
        };
        BalanceOverviewAccount: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["AccountTypeEnum"];
            /** Format: decimal */
            balance: string;
        };
        Category: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
        };
        CategoryBreakdown: {
            year: number;
            month: number;
            categories: components["schemas"]["CategoryBreakdownItem"][];
        };
        CategoryBreakdownItem: {
            /** Format: uuid */
            category_id: string | null;
            category_name: string | null;
            /** Format: decimal */
            income: string;
            /** Format: decimal */
            expense: string;
        };
        /**
         * @description 自訂 Token 序列化器
         *     在 JWT payload 中加入額外的使用者資訊
         */
        CustomTokenObtainPair: {
            email: string;
            password: string;
        };
        LoginResponse: {
            access: string;
            refresh: string;
            user: components["schemas"]["LoginResponseUser"];
        };
        LoginResponseUser: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email: string;
            role: string;
        };
        LogoutRequest: {
            refresh: string;
        };
        LogoutResponse: {
            message: string;
        };
        MonthSummary: {
            year: number;
            month: number;
            /** Format: decimal */
            income: string;
            /** Format: decimal */
            expense: string;
            /** Format: decimal */
            net: string;
        };
        PaginatedAccountList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Account"][];
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedRecurringRuleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RecurringRule"][];
        };
        PaginatedSavingsGoalList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SavingsGoal"][];
        };
        PaginatedTagList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Tag"][];
        };
        PaginatedTransactionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Transaction"][];
        };
        PatchedAccount: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            type?: components["schemas"]["AccountTypeEnum"];
            /** Format: decimal */
            readonly balance?: string;
            is_default?: boolean;
        };
        PatchedCategory: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
        };
        PatchedRecurringRule: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            account?: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: decimal */
            amount?: string;
            type?: components["schemas"]["TransactionTypeEnum"];
            name?: string;
            description?: string;
            day_of_month?: number;
            is_active?: boolean;
            /** Format: date */
            readonly next_run_date?: string;
            readonly account_name?: string;
            readonly category_name?: string | null;
        };
        PatchedSavingsGoal: {
            /** Format: uuid */
            readonly id?: string;
            period_type?: components["schemas"]["PeriodTypeEnum"];
            year?: number;
            month?: number | null;
            /** Format: decimal */
            amount?: string;
        };
        PatchedTag: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
        };
        PatchedTransaction: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            account?: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: decimal */
            amount?: string;
            type?: components["schemas"]["TransactionTypeEnum"];
            name?: string;
            description?: string;
            /** Format: date-time */
            occurred_at?: string;
            tags?: string[];
            /** Format: uuid */
            readonly source_rule?: string | null;
            readonly account_name?: string;
            readonly category_name?: string | null;
            readonly tag_names?: string[];
        };
        /** @description 使用者序列化器 */
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly created_at?: string;
        };
        /**
         * @description * `monthly` - 月度
         *     * `yearly` - 年度
         * @enum {string}
         */
        PeriodTypeEnum: "monthly" | "yearly";
        RangeSummary: {
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
            /** Format: decimal */
            income: string;
            /** Format: decimal */
            expense: string;
            /** Format: decimal */
            net: string;
        };
        RecurringRule: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            account: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: decimal */
            amount: string;
            type: components["schemas"]["TransactionTypeEnum"];
            name?: string;
            description?: string;
            day_of_month: number;
            is_active?: boolean;
            /** Format: date */
            readonly next_run_date: string;
            readonly account_name: string;
            readonly category_name: string | null;
        };
        RegisterResponse: {
            message: string;
            user: components["schemas"]["User"];
            tokens: components["schemas"]["RegisterResponseTokens"];
        };
        RegisterResponseTokens: {
            access: string;
            refresh: string;
        };
        /**
         * @description * `admin` - 管理員
         *     * `staff` - 員工
         *     * `member` - 會員
         * @enum {string}
         */
        RoleEnum: "admin" | "staff" | "member";
        SavingsGoal: {
            /** Format: uuid */
            readonly id: string;
            period_type: components["schemas"]["PeriodTypeEnum"];
            year: number;
            month?: number | null;
            /** Format: decimal */
            amount: string;
        };
        SavingsGoalStatus: {
            period_type: components["schemas"]["PeriodTypeEnum"];
            year: number;
            month: number | null;
            /** Format: decimal */
            goal_amount: string | null;
            /** Format: decimal */
            actual_net: string;
            /** Format: decimal */
            difference: string | null;
            achieved: boolean | null;
        };
        Tag: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
        };
        TagBreakdown: {
            year: number;
            month: number;
            tags: components["schemas"]["TagBreakdownItem"][];
        };
        TagBreakdownItem: {
            /** Format: uuid */
            tag_id: string;
            tag_name: string;
            /** Format: decimal */
            income: string;
            /** Format: decimal */
            expense: string;
        };
        TodaySummary: {
            /** Format: date */
            date: string;
            /** Format: decimal */
            expense: string;
            /** Format: decimal */
            income: string;
            /** Format: decimal */
            net: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenVerify: {
            token: string;
        };
        Transaction: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            account: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: decimal */
            amount: string;
            type: components["schemas"]["TransactionTypeEnum"];
            name?: string;
            description?: string;
            /** Format: date-time */
            occurred_at?: string;
            tags?: string[];
            /** Format: uuid */
            readonly source_rule: string | null;
            readonly account_name: string;
            readonly category_name: string | null;
            readonly tag_names: string[];
        };
        /**
         * @description * `income` - 收入
         *     * `expense` - 支出
         * @enum {string}
         */
        TransactionTypeEnum: "income" | "expense";
        /** @description 使用者序列化器 */
        User: {
            /** Format: uuid */
            readonly id: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            phone?: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description 使用者註冊序列化器 */
        UserRegister: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
            phone?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPair"];
                "multipart/form-data": components["schemas"]["CustomTokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegister"];
                "multipart/form-data": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
    auth_users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    auth_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    ledger_accounts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountList"];
                };
            };
        };
    };
    ledger_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Account"];
                "application/x-www-form-urlencoded": components["schemas"]["Account"];
                "multipart/form-data": components["schemas"]["Account"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    ledger_accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    ledger_accounts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Account"];
                "application/x-www-form-urlencoded": components["schemas"]["Account"];
                "multipart/form-data": components["schemas"]["Account"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    ledger_accounts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_accounts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAccount"];
                "multipart/form-data": components["schemas"]["PatchedAccount"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    ledger_categories_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    ledger_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    ledger_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    ledger_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    ledger_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    ledger_recurring_rules_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecurringRuleList"];
                };
            };
        };
    };
    ledger_recurring_rules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringRule"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurringRule"];
                "multipart/form-data": components["schemas"]["RecurringRule"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
        };
    };
    ledger_recurring_rules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this recurring rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
        };
    };
    ledger_recurring_rules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this recurring rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringRule"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurringRule"];
                "multipart/form-data": components["schemas"]["RecurringRule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
        };
    };
    ledger_recurring_rules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this recurring rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_recurring_rules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this recurring rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecurringRule"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecurringRule"];
                "multipart/form-data": components["schemas"]["PatchedRecurringRule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRule"];
                };
            };
        };
    };
    ledger_reports_balance_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceOverview"];
                };
            };
        };
    };
    ledger_reports_balance_history_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceHistoryAccount"][];
                };
            };
        };
    };
    ledger_reports_savings_goal_status_retrieve: {
        parameters: {
            query?: {
                /** @description 月 1–12；帶＝查月度目標、省略＝查年度目標（非預設當月）。 */
                month?: number;
                /** @description 西元年 1–9999；未帶＝當前時區的今年。 */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalStatus"];
                };
            };
        };
    };
    ledger_reports_summary_retrieve: {
        parameters: {
            query?: {
                /** @description 月 1–12；未帶＝當前時區的本月。 */
                month?: number;
                /** @description 西元年 1–9999；未帶＝當前時區的今年。 */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthSummary"];
                };
            };
        };
    };
    ledger_reports_summary_by_category_retrieve: {
        parameters: {
            query?: {
                /** @description 月 1–12；未帶＝當前時區的本月。 */
                month?: number;
                /** @description 西元年 1–9999；未帶＝當前時區的今年。 */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryBreakdown"];
                };
            };
        };
    };
    ledger_reports_summary_by_tag_retrieve: {
        parameters: {
            query?: {
                /** @description 月 1–12；未帶＝當前時區的本月。 */
                month?: number;
                /** @description 西元年 1–9999；未帶＝當前時區的今年。 */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagBreakdown"];
                };
            };
        };
    };
    ledger_reports_summary_range_retrieve: {
        parameters: {
            query: {
                /** @description 迄日（含當日），YYYY-MM-DD；須 start ≤ end。 */
                end: string;
                /** @description 起日（含），YYYY-MM-DD。 */
                start: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeSummary"];
                };
            };
        };
    };
    ledger_reports_today_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodaySummary"];
                };
            };
        };
    };
    ledger_savings_goals_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSavingsGoalList"];
                };
            };
        };
    };
    ledger_savings_goals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["SavingsGoal"];
                "multipart/form-data": components["schemas"]["SavingsGoal"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    ledger_savings_goals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this savings goal. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    ledger_savings_goals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this savings goal. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["SavingsGoal"];
                "multipart/form-data": components["schemas"]["SavingsGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    ledger_savings_goals_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this savings goal. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_savings_goals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this savings goal. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSavingsGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSavingsGoal"];
                "multipart/form-data": components["schemas"]["PatchedSavingsGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoal"];
                };
            };
        };
    };
    ledger_tags_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTagList"];
                };
            };
        };
    };
    ledger_tags_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tag"];
                "application/x-www-form-urlencoded": components["schemas"]["Tag"];
                "multipart/form-data": components["schemas"]["Tag"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    ledger_tags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tag. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    ledger_tags_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tag. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tag"];
                "application/x-www-form-urlencoded": components["schemas"]["Tag"];
                "multipart/form-data": components["schemas"]["Tag"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    ledger_tags_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tag. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_tags_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tag. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTag"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTag"];
                "multipart/form-data": components["schemas"]["PatchedTag"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    ledger_transactions_list: {
        parameters: {
            query?: {
                account?: string;
                amount_max?: number;
                amount_min?: number;
                category?: string;
                occurred_after?: string;
                occurred_before?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                /** @description Multiple values may be separated by commas. */
                tags_all?: string[];
                /** @description Multiple values may be separated by commas. */
                tags_any?: string[];
                /**
                 * @description * `income` - 收入
                 *     * `expense` - 支出
                 */
                type?: "expense" | "income";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactionList"];
                };
            };
        };
    };
    ledger_transactions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    ledger_transactions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    ledger_transactions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    ledger_transactions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ledger_transactions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTransaction"];
                "multipart/form-data": components["schemas"]["PatchedTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
}
